[package]
name = 'charts'
version = '0.0.0'
edition = '2021'

[build-dependencies]
tauri-build = { version = '^1.5' , features = [] }

[dependencies]
tauri = { version = '^1.5' , features = [ "window-show", "window-hide", "window-close", "system-tray"] }
serde = { version = '^1.0' }
serde_json = { version = '^1.0' }
rust-ini = { version = '^0.20' }

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

[features]
custom-protocol = ["tauri/custom-protocol"]
