[package]
name = 'chats'
version = '0.0.0'
edition = '2021'

[build-dependencies]
tauri-build = { features = [] }

[dependencies]
tauri = { version = "*", features = [ "window-create", "notification-all", "path-all", "dialog-message", "fs-read-file", "dialog-save", "dialog-open", "system-tray", "window-close", "window-hide", "window-show"] }
serde = "*"
serde_json = "*"
rust-ini = "*"
sqlite = "*"
once_cell = "*"
uuid = "*"
chrono = "*"

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

[features]
custom-protocol = ["tauri/custom-protocol"]
